### ISSUE TITLE
os.join gives bad url on windows

### ISSUE THREAD

**Issue by tattonchantry** [rasbt/python-machine-learning-book-3rd-edition#107]
```
s = os.path.join('https://archive.ics.uci.edu', 'ml',
                 'machine-learning-databases', 'iris','iris.data')
```
on windows gives: https://archive.ics.uci.edu\ml\machine-learning-databases\iris\iris.data
which does not work.  I would do a pull request and suggest replacing it with:
```
s = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
```
but, I don't know if there is a reason for doing the join.

**Comment by rasbt** [comment]
Oh interesting. I have no idea about how Windows works and a reader of the 2nd edition emailed me saying that there were problems with the forward slashes and that Windows uses backslashes for links and file paths, which is why I replaced that with the join, because it would take care of it. Maybe I was mistaken there. In that case changing it like you suggest would obviously make sense.

**Comment by tattonchantry** [comment]
Wow. Thanks for a response. I felt silly mentioning it. It means a lot that you responded. I put it in a pull request, and I will close this.
