### ISSUE TITLE
Error problem in chapter 15

### ISSUE THREAD

**Issue by dydavuth** [rasbt/python-machine-learning-book-3rd-edition#175]
TypeError                                 Traceback (most recent call last)
<ipython-input-27-ad9672e4bbf7> in <module>
     12     tf.print(
     13         'CCE (w Probas): {:.4f}'.format(
---> 14         cce_probas(y_true=[[0, 0, 1]], y_pred=probas)),
     15         '(w Logits): {:.4f}'.format(
     16         cce_logits(y_true=[[0, 0, 1]], y_pred=logits)))

TypeError: 'int' object is not callable

**Comment by rasbt** [comment]
I just tried the chapter 15 code on Google Colab and it works fine for me. I suspect your issue is probably due to a tensorflow version issue. I.e., there is this section 

```python
if Version(tf.__version__) >= '2.3.0':
    tf.print(
        'CCE (w Probas): {:.4f}'.format(
        cce_probas(y_true=[[0, 0, 1]], y_pred=probas)),
        '(w Logits): {:.4f}'.format(
        cce_logits(y_true=[[0, 0, 1]], y_pred=logits)))
    
else:
    tf.print(
        'CCE (w Probas): {:.4f}'.format(
        cce_probas(y_true=[0, 0, 1], y_pred=probas)),
        '(w Logits): {:.4f}'.format(
        cce_logits(y_true=[0, 0, 1], y_pred=logits)))
```

in the code here on GitHub that is probably related. I suggest downloading the latest code from this GitHub repo and see if it fixed the issue.
